version: "3.7"
services:
  wordpress:
    image: santosalves/wordpress_projeto05:latest
    ports:
    - "80:80"
    environment:
      WORDPRESS_DB_HOST: mysql
      WORDPRESS_DB_USER: projeto04
      WORDPRESS_DB_PASSWORD: senac@123
      WORDPRESS_DB_NAME: projeto_integrador04
volumes:
  - wordpress_dados
