version: "3.7"
services:
  wordpress:
    image: santosalves/wordpress_projeto05:latest
    ports:
    - "80:80"
    environment:
      WORDPRESS_DB_HOST: wordpress-db-prod.caqz1l0qgvir.us-east-1.rds.amazonaws.com 
      WORDPRESS_DB_USER: senac
      WORDPRESS_DB_PASSWORD: senac123
      WORDPRESS_DB_NAME: projeto_integrador05
volumes:
  wordpress_dados:
