version: "3.7"
services:
  wordpress:
    image: santosalves/wordpress_projeto05:latest
    ports:
    - "80:80"
    environment:
      WORDPRESS_DB_HOST: db.internal-santosalves-labs.tk
      WORDPRESS_DB_USER: senac
      WORDPRESS_DB_PASSWORD: senac123
      WORDPRESS_DB_NAME: projeto_integrador05
     deploy:
      mode: replicated
      replicas: 2
      resources:
        limits:
          cpus: '0.50'
          memory: 320M
        reservations:
          cpus: '0.25'
          memory: 200M
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s
    volumes:
    - wordpress_dados:/var/www/html

volumes:
  wordpress_dados:
