AWSTemplateFormatVersion: 2010-09-09
Description: Criacao do NAT-GATEWAY e do ALB

Parameters: 
  PUBPROD01:
    Type: String
    Default: subnet-07fd9946026043b05
  PUBPROD02:
    Type: String
    Default: subnet-00a516a8eb719f134
  PUBPROD03:
    Type: String
    Default: subnet-058216ce359aabae3
  PRIVROUTE:
    Type: String
    Default: rtb-0a59823976b57b5eb
Mappings: 
  {}
Resources: 
  NAT:
   Type: AWS::EC2::NatGateway
   Properties:
      AllocationId:
         Fn::GetAtt:
         - EIP
         - AllocationId
      SubnetId:
         Ref: PUBPROD01
      Tags:
      - Key: Name
        Value: NAT-PROD01
  EIP:
    Type: AWS::EC2::EIP
    Properties:
        Domain: vpc
        Tags:
          - Key: Name
            Value: NAT-PROD01
  Route:
    Type: AWS::EC2::Route
    Properties:
        RouteTableId:
          Ref: PRIVROUTE
        DestinationCidrBlock: 0.0.0.0/0
        NatGatewayId:
          Ref: NAT
  ALB:
    Type: AWS::ElasticLoadBalancingV2::LoadBalancer
    Properties:
      Name: LOAD-BALANCE-PROD
      Scheme: internet-facing
      SecurityGroups: 
        - sg-044532a72f2d2ba47
      Subnets: 
        - Ref: PUBPROD01
        - Ref: PUBPROD02
        - Ref: PUBPROD03
      Tags: 
        - Key: Name
          Value: LOAD-BALANCE-PROD
        - Key: Created
          Value: CloudFormation
  WORDPRESSTG:
    Type: AWS::ElasticLoadBalancingV2::Listener
    Properties:
      DefaultActions: 
        - Type: forward
          TargetGroupArn: arn:aws:elasticloadbalancing:us-east-1:946553465797:targetgroup/SWARM-WORDPRESS/f37ed16131728247
      LoadBalancerArn: !Ref ALB
      Port: 80
      Protocol: HTTP
  NODEEXPORTERTG:
    Type: AWS::ElasticLoadBalancingV2::Listener
    Properties:
      DefaultActions: 
        - Type: forward
          TargetGroupArn: arn:aws:elasticloadbalancing:us-east-1:946553465797:targetgroup/SWARM-NODE-EXPORTER/4e76bd011b39910a
      LoadBalancerArn: !Ref ALB
      Port: 9100
      Protocol: HTTP
  PROMETHEUSTG:
    Type: AWS::ElasticLoadBalancingV2::Listener
    Properties:
      DefaultActions: 
        - Type: forward
          TargetGroupArn: arn:aws:elasticloadbalancing:us-east-1:946553465797:targetgroup/SWARM-PROMETHEUS/c0740c5e05ed61ff
      LoadBalancerArn: !Ref ALB
      Port: 9090
      Protocol: HTTP
  GRAFANATG:
    Type: AWS::ElasticLoadBalancingV2::Listener
    Properties:
      DefaultActions: 
        - Type: forward
          TargetGroupArn: arn:aws:elasticloadbalancing:us-east-1:946553465797:targetgroup/SWARM-GRAFANA/d1b461daeb02e0ce
      LoadBalancerArn: !Ref ALB
      Port: 3000
      Protocol: HTTP
  GRAYLOGTG:
    Type: AWS::ElasticLoadBalancingV2::Listener
    Properties:
      DefaultActions: 
        - Type: forward
          TargetGroupArn: arn:aws:elasticloadbalancing:us-east-1:946553465797:targetgroup/SWARM-GRAYLOG/65acf390713ec558
      LoadBalancerArn: !Ref ALB
      Port: 9000
      Protocol: HTTP
  INPUTRSYSLOGTG:
    Type: AWS::ElasticLoadBalancingV2::Listener
    Properties:
      DefaultActions: 
        - Type: forward
          TargetGroupArn: arn:aws:elasticloadbalancing:us-east-1:946553465797:targetgroup/INPUT-RSYSLOG/0992bcd098343cfb
      LoadBalancerArn: !Ref ALB
      Port: 12201
      Protocol: HTTP
Outputs:
  {}